### ISSUE TITLE
Create streamlit frontend mock

### ISSUE THREAD

**Issue by Zaubeerer** [lucasiragusa/landingpermit_app#2]

**Comment by yaninahabeleva** [comment]
1. Only .TXT files are excepted on "Comparative Doc Generation" page but headers say "Insert base SSIM File" and "Insert new SSIM File"
<img width="1486" alt="ssim" src="https://github.com/lucasiragusa/landingpermit_app/assets/75788568/539086d1-a47c-4ca0-ba80-cac9f61844c2">

**Comment by Zaubeerer** [comment]
Can you push your code and ask the question in the PR? 

You can explicitly filter for the file type or keep it open. 

I guess that in your code, it filters for `TXT` file, but you can deactivate that ;-)

**Comment by yaninahabeleva** [comment]
2. User can manually type in any random date (even the one that does not make sense)
<img width="1330" alt="man" src="https://github.com/lucasiragusa/landingpermit_app/assets/75788568/41c651de-19ab-452e-af99-56149c31fc04">

**Comment by Zaubeerer** [comment]
Another bug that you can best push to a related PR with the related code :)
